import { writeFile } from 'fs/promises';
import { resolve } from 'path';
import type { ReviewMetadata } from '../types.js';

export class ReportGenerator {
  async generate(
    review: string,
    metadata: ReviewMetadata,
    outputPath: string
  ): Promise<void> {
    const report = this.formatReport(review, metadata);
    const fullPath = resolve(process.cwd(), outputPath);

    try {
      await writeFile(fullPath, report, 'utf-8');
      console.log(`\n✅ Review saved to: ${outputPath}`);
    } catch (error: any) {
      throw new Error(`Failed to write report: ${error.message}`);
    }
  }

  private formatReport(review: string, metadata: ReviewMetadata): string {
    return `# Code Review Report

**Generated**: ${metadata.timestamp}
**Branch**: \`${metadata.branch}\`
**Base Branch**: \`${metadata.baseBranch}\`
**Model**: ${metadata.model}
**Files Reviewed**: ${metadata.filesReviewed}
**Lines Changed**: ${metadata.linesChanged}

---

${review}

---

*Generated by MR Review Agent*
`;
  }
}
